"use client";

import { useEffect, useMemo, useState } from "react";
import { getBrowserClient } from "@/lib/supabase-browser";

type Question = { subject: string; text: string; options: string[]; answer?: number; note: string; itemId?: string };
const bank: Question[] = [
  { subject: "Bahasa Melayu", text: "Pilih ayat yang menggunakan kata kerja transitif dengan betul.", options: ["Adik tidur di sofa.", "Ibu membaca novel itu.", "Burung itu terbang tinggi.", "Mereka berjalan perlahan."], answer: 1, note: "‘Membaca’ diikuti objek ‘novel itu’." },
  { subject: "Matematik", text: "Nilai bagi 3(2x − 5) apabila x = 4 ialah", options: ["9", "12", "15", "24"], answer: 0, note: "3(2 × 4 − 5) = 9." },
  { subject: "Sejarah", text: "Apakah tujuan utama penubuhan Malayan Union pada tahun 1946?", options: ["Meluaskan kuasa raja Melayu", "Menyatukan pentadbiran negeri Melayu", "Menghapuskan kewarganegaraan", "Menubuhkan kerajaan persekutuan"], answer: 1, note: "Pentadbirannya disatukan di bawah kerajaan pusat." },
  { subject: "Biologi", text: "Struktur sel manakah mengawal semua aktiviti sel?", options: ["Membran sel", "Mitokondrion", "Nukleus", "Vakuol"], answer: 2, note: "Nukleus mengawal aktiviti sel." },
  { subject: "English", text: "Choose the sentence with the correct subject-verb agreement.", options: ["The students is ready.", "Each books are useful.", "Neither answer is correct.", "My friends goes home."], answer: 2, note: "‘Neither’ takes the singular verb ‘is’." },
];
const leaders = [["1","Nur Aina","20","08:42"],["2","陈宇轩","19","09:14"],["3","Siti Farah","19","10:02"],["4","Arjun K.","18","08:57"],["5","林嘉恩","18","11:20"]];
const streakLeaders = [["1","陈宇轩","42","今天"],["2","Nur Aina","31","今天"],["3","林嘉恩","21","今天"],["4","Siti Farah","18","昨天"],["5","Arjun K.","14","今天"]];
const subjects = ["Bahasa Melayu", "Matematik", "Sejarah", "Biologi", "English"];
const Logo = () => <div className="logo"><span>SPM</span><b>龙虎榜</b></div>;

export default function Home() {
  const [tab, setTab] = useState<"home"|"quiz"|"rank"|"teacher">("home");
  const [n, setN] = useState(0); const [answers, setAnswers] = useState<(number | undefined)[]>([]); const [done, setDone] = useState(false); const [isTeacher, setTeacher] = useState(false); const [choosing, setChoosing] = useState(false); const [selectedSubject, setSelectedSubject] = useState("Matematik"); const [quiz, setQuiz] = useState<Question[]>([]); const [rankMode, setRankMode] = useState<"daily"|"streak">("daily"); const [session, setSession] = useState<any>(null); const [quizId, setQuizId] = useState<string | null>(null); const [serverScore, setServerScore] = useState<number | null>(null); const [message, setMessage] = useState(""); const [rankRows,setRankRows]=useState<string[][]>([]); const [teacherUploads,setTeacherUploads]=useState<any[]>([]); const [teacherQuestions,setTeacherQuestions]=useState<any[]>([]);
  const q = quiz[n] ?? bank[0]!; const localScore = useMemo(() => answers.reduce<number>((x,a,i) => x + (a === quiz[i]?.answer ? 1 : 0), 0), [answers, quiz]); const score = serverScore ?? localScore; const shownRows=rankRows.length?rankRows:(rankMode==="daily"?leaders:streakLeaders);
  useEffect(() => { const client = getBrowserClient(); if (!client) return; client.auth.getSession().then(({ data }) => setSession(data.session)); const { data } = client.auth.onAuthStateChange((_event, next) => setSession(next)); return () => data.subscription.unsubscribe(); }, []);
  async function login(){const client=getBrowserClient(); if(!client){setMessage("登录配置尚未完成，请稍后再试。");return;} await client.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin}})}
  async function callApi(path:string, init?:RequestInit){if(!session?.access_token) throw new Error("请先使用 Google 登录。"); const response=await fetch(path,{...init,headers:{"content-type":"application/json",authorization:`Bearer ${session.access_token}`,...init?.headers}}); const body=await response.json(); if(!response.ok) throw new Error(body.error||"请求失败"); return body;}
  async function loadAccount(){try{const data=await callApi("/api/me");setTeacher(data.profile?.role==="teacher");}catch{/* Account data is optional until login is configured. */}}
  async function verifyTeacher(){try{const inviteCode=window.prompt("请输入教师邀请码");if(!inviteCode)return;await callApi("/api/teacher/verify",{method:"POST",body:JSON.stringify({inviteCode})});setTeacher(true);setMessage("教师权限已启用。");}catch(error){setMessage(error instanceof Error?error.message:"验证失败");}}
  async function uploadPdf(file:File){try{if(!session?.access_token)throw new Error("请先使用 Google 登录。");const subject=window.prompt("请输入这份试卷的科目，例如 Matematik")||"";const form=new FormData();form.append("file",file);form.append("subject",subject);const response=await fetch("/api/teacher/uploads",{method:"POST",headers:{authorization:`Bearer ${session.access_token}`},body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||"上传失败");setMessage(`${data.upload.filename} 已上传，现为待审核状态。`);}catch(error){setMessage(error instanceof Error?error.message:"上传失败");}}
  async function loadRanking(){try{const data=await fetch(`/api/leaderboard?kind=${rankMode}${rankMode==="daily"?`&subject=${encodeURIComponent(selectedSubject)}`:""}`).then((response)=>response.ok?response.json():Promise.reject());setRankRows(data.entries.map((item:any,index:number)=>[String(item.rank??index+1),item.name||item.display_name,String(item.score??item.streak_days),item.completedAt?new Date(item.completedAt).toLocaleTimeString("en-MY",{hour:"2-digit",minute:"2-digit"}):item.last_checkin_date||"—"]));}catch{/* Keep the lightweight preview rows until production data is available. */}}
  async function loadTeacherData(){try{const [uploads,questions]=await Promise.all([callApi("/api/teacher/uploads"),callApi("/api/teacher/questions")]);setTeacherUploads(uploads.uploads||[]);setTeacherQuestions(questions.questions||[]);}catch(error){setMessage(error instanceof Error?error.message:"无法读取教师资料");}}
  async function createManualQuestion(){try{const subject=window.prompt("科目")?.trim();const prompt=window.prompt("题干")?.trim();const optionA=window.prompt("A 选项")?.trim();const optionB=window.prompt("B 选项")?.trim();const optionC=window.prompt("C 选项")?.trim();const optionD=window.prompt("D 选项")?.trim();const correctOption=window.prompt("正确答案（A / B / C / D）")?.trim().toUpperCase();if(!subject||!prompt||!optionA||!optionB||!optionC||!optionD||!correctOption)return;await callApi("/api/teacher/questions",{method:"POST",body:JSON.stringify({subject,prompt,optionA,optionB,optionC,optionD,correctOption})});setMessage("题目草稿已建立。审核后点击发布。 ");await loadTeacherData();}catch(error){setMessage(error instanceof Error?error.message:"无法建立题目");}}
  async function confirmAnswer(id:string){try{const correctOption=window.prompt("确认正确答案（A / B / C / D）")?.trim().toUpperCase();if(!correctOption)return;await callApi("/api/teacher/questions",{method:"PATCH",body:JSON.stringify({id,correctOption})});setMessage("正确答案已确认，现在可以发布。");await loadTeacherData();}catch(error){setMessage(error instanceof Error?error.message:"答案确认失败");}}
  async function publishQuestion(id:string){try{await callApi("/api/teacher/questions",{method:"PATCH",body:JSON.stringify({id,publish:true})});setMessage("题目已发布，会进入对应科目的学生题库。");await loadTeacherData();}catch(error){setMessage(error instanceof Error?error.message:"发布失败；请先确认正确答案。 ");}}
  useEffect(()=>{if(tab==="rank")loadRanking();},[tab,rankMode,selectedSubject]);
  useEffect(()=>{if(isTeacher)loadTeacherData();},[isTeacher]);
  useEffect(()=>{if(session){loadAccount();loadDaily().catch(()=>undefined);}},[session]);
  async function loadDaily(){const data=await callApi("/api/daily"); if(!data.quiz)return; setQuizId(data.quiz.id); setSelectedSubject(data.quiz.subject); setDone(data.quiz.status==="submitted"); setServerScore(data.quiz.correct_count); setAnswers(data.quiz.items.map((item:any)=>item.selectedOption?"ABCD".indexOf(item.selectedOption):undefined)); setQuiz(data.quiz.items.map((item:any)=>({itemId:item.id,subject:item.question.subject,text:item.question.prompt,options:item.question.options,answer:item.question.correctOption?"ABCD".indexOf(item.question.correctOption):undefined,note:item.question.explanation||""})));}
  async function begin(subject = selectedSubject){try{setMessage("");setSelectedSubject(subject);setN(0);setChoosing(false);if(session){const data=await callApi("/api/daily",{method:"POST",body:JSON.stringify({subject})});setQuizId(data.id);await loadDaily();}else{const pool=bank.filter((item)=>item.subject===subject);setQuiz(Array.from({length:20},(_,i)=>pool[i%pool.length]));setAnswers([]);setDone(false);setServerScore(null);}setTab("quiz")}catch(error){setMessage(error instanceof Error?error.message:"无法开始任务");}}
  function pick(a:number){if(answers[n] !== undefined)return; const copy=[...answers];copy[n]=a;setAnswers(copy)}
  async function advance(){if(n!==quiz.length-1){setN(n+1);return;}try{if(session&&quizId){const data=await callApi("/api/daily",{method:"PATCH",body:JSON.stringify({quizId,answers:quiz.map((item,index)=>({itemId:item.itemId,option:"ABCD".charAt(answers[index] ?? -1)}))})});setServerScore(data.correct);await loadDaily();}setDone(true)}catch(error){setMessage(error instanceof Error?error.message:"提交失败");}}
  return <main>
    <header><button className="brand" onClick={()=>setTab("home")}><Logo/></button><div className="partner"><span>Powered by</span><img src="/myguru-logo.png" alt="My Guru Education" /></div><nav><button onClick={()=>setTab("rank")}>今日排行榜</button><button onClick={()=>setTab("teacher")}>教师中心</button></nav><button className="teacher-mobile" onClick={()=>setTab("teacher")}>教师中心</button><button className="user" onClick={session?()=>loadDaily().catch(()=>undefined):login}><i>{session?"我":"G"}</i><span><b>{session?.user?.user_metadata?.full_name||session?.user?.email||"Google 登录"}</b><small>{session?"查看今日任务":"登录后保存成绩"}</small></span></button></header>
    {message&&<div className="app-message" role="status">{message}<button onClick={()=>setMessage("")}>×</button></div>}
    {tab === "home" && <section className="wrap home">
      <div className="hero"><div><p className="eyebrow">MONDAY · 17 AUGUST</p><h1>今天，也比昨天<br/>更靠近 <em>A+</em>。</h1><p>选择今天要冲刺的科目，完成 20 题点亮学习记录。</p><button className="primary light" onClick={()=>setChoosing(true)}>选择科目开始　→</button></div><aside><p>本月学习足迹</p><div className="week">{"MTWTFSS".split("").map((x,i)=><span className={i<5?"checked":""} key={i}><b>{x}</b><i>{i<5?"✓":""}</i></span>)}</div><div className="streak"><strong>7</strong><span>天连续打卡<br/>继续保持！</span></div></aside></div>
      {choosing && <section className="subject-picker"><div><p className="eyebrow">CHOOSE YOUR SUBJECT</p><h2>今天想挑战哪一科？</h2><p>每日首轮选定后不可更换，完成该科 20 题将计入日榜。</p></div><div className="subject-grid">{subjects.map((subject)=><button className={subject===selectedSubject?"chosen":""} onClick={()=>setSelectedSubject(subject)} key={subject}><b>{subject}</b><small>20 题练习</small></button>)}</div><footer><button className="secondary" onClick={()=>setChoosing(false)}>稍后再说</button><button className="primary" onClick={()=>begin()}>开始 {selectedSubject}　→</button></footer></section>}
      <div className="cards"><article><div className="title"><div><p className="eyebrow">DAILY MISSION</p><h2>今日任务</h2></div><b className="pill">{selectedSubject}</b></div><div className="mission"><div className="circle"><b>0%</b><small>完成度</small></div><div><h3>{selectedSubject} · 20 题</h3><p>自主选择科目 · 完成后计入全校日榜</p><div className="bar"><i/></div><small>0 / 20 题</small></div></div><button className="link" onClick={()=>setChoosing(true)}>更换科目 / 开始答题　→</button></article><article><div className="title"><div><p className="eyebrow">SCHOOL RANKING</p><h2>{rankMode==="daily"?"今日龙虎榜":"连续打卡榜"}</h2></div><button className="link" onClick={()=>setTab("rank")}>查看全部　→</button></div><div className="mini">{shownRows.slice(0,3).map(([r,name,points])=><div key={r}><strong>{r}</strong><i>{name[0]}</i><b>{name}</b><em>{points} <small>{rankMode==="daily"?"题正确":"天连续"}</small></em></div>)}</div><button className="notice notice-button" onClick={()=>setRankMode(rankMode==="daily"?"streak":"daily")}>{rankMode==="daily"?"查看连续打卡榜 🔥":"返回每日答题榜"}</button></article></div>
    </section>}
    {tab === "quiz" && <section className="wrap quiz">
      {!done ? <><div className="quizhead"><button className="link" onClick={()=>setTab("home")}>← 返回</button><div><span>{selectedSubject} · 第 {n+1} / 20 题</span><div className="bar"><i style={{width:`${((n+(answers[n]!==undefined?1:0))/20)*100}%`}}/></div></div><span>◷ 19:46</span></div><article className="question"><b className="subject">{q.subject}</b><h1>{q.text}</h1><div className="options">{q.options.map((v,i)=><button key={v} className={answers[n]===i?"selected":""} onClick={()=>pick(i)}><b>{"ABCD".charAt(i)}</b><span>{v}</span></button>)}</div><footer><small>选择一个答案后继续</small><button disabled={answers[n]===undefined} className="primary" onClick={advance}>{n===quiz.length-1?"提交答案":"下一题　→"}</button></footer></article></> : <article className="result"><div>✦　✧　✦</div><p className="eyebrow">{selectedSubject.toUpperCase()} · DAILY MISSION COMPLETE</p><h1>今日挑战完成！</h1><strong>{score}<small>/ 20 题答对</small></strong><p>你的正式每日任务已提交。继续练习不会影响今日排名。</p><button className="primary" onClick={()=>setTab("rank")}>查看今日排名</button><button className="secondary" onClick={()=>setTab("home")}>返回首页</button><section>{quiz.map((x,i)=><div key={`${x.subject}-${i}`}><b className={answers[i]===x.answer?"ok":"bad"}>{answers[i]===x.answer?"✓":"×"}</b><span>{i+1}. {x.subject}</span><small>{answers[i]===x.answer?"正确":`答案：${"ABCD".charAt(x.answer ?? -1)} · ${x.note}`}</small></div>)}</section></article>}</section>}
    {tab === "rank" && <section className="wrap page"><div className="heading"><div><p className="eyebrow">MALAYSIA TIME</p><h1>{rankMode==="daily"?"今日龙虎榜":"连续打卡榜 🔥"}</h1><p>{rankMode==="daily"?"按首轮 20 题正确数排列。相同成绩以完成时间排序。":"按连续完成每日任务的天数排列，每天午夜后更新。"}</p></div><b>{rankMode==="daily"?"♛":"🔥"}</b></div><div className="rank-modes"><button className={rankMode==="daily"?"active":""} onClick={()=>setRankMode("daily")}>每日答题榜</button><button className={rankMode==="streak"?"active":""} onClick={()=>setRankMode("streak")}>连续打卡榜</button></div>{rankMode==="daily"&&<div className="rank-subjects">{subjects.map((subject)=><button className={subject===selectedSubject?"active":""} onClick={()=>setSelectedSubject(subject)} key={subject}>{subject}</button>)}</div>}<article className="table"><div className="thead"><span>排名</span><span>学生</span><span>{rankMode==="daily"?"正确题数":"连续打卡"}</span><span>{rankMode==="daily"?"完成时间":"最近打卡"}</span></div>{shownRows.map(([r,name,points,time])=><div className="tr" key={`${r}-${name}`}><strong>{r}</strong><span><i>{name[0]}</i><b>{name}</b></span><span><b>{points}</b> {rankMode==="daily"?"/ 20":"天"}</span><small>{time}</small></div>)}<div className="tr mine"><strong>—</strong><span><i>我</i><b>{session?.user?.user_metadata?.full_name||"你"}</b></span><span>{rankMode==="daily"?"尚未完成":"—"}</span><small>—</small></div></article></section>}
    {tab === "teacher" && <section className="wrap page"><div className="teacherhero"><div><p className="eyebrow">TEACHER STUDIO</p><h1>让每一份练习，<br/>成为学生的下一步。</h1><p>上传文字型 PDF，审核题目后发布到全校练习题库。</p></div><b>A<small>B　C　D</small></b></div>{!isTeacher?<article className="invite"><i>⌁</i><div><h2>进入教师中心</h2><p>首次使用请输入教师邀请码。验证后，此 Google 帐号将获得题库管理权限。</p></div><button className="primary" onClick={verifyTeacher}>验证邀请码　→</button></article>:<><article className="upload"><i>↑</i><h2>上传新的试卷</h2><p>支持文字型 PDF · 上传后会安全保存为待审核资料，题目必须人工审核、填写答案后才可发布。</p><label className="secondary">选择 PDF 文件<input type="file" accept="application/pdf" hidden onChange={(event)=>{const file=event.target.files?.[0];if(file)uploadPdf(file)}}/></label><button className="primary" onClick={createManualQuestion}>手动新增题目</button></article><article className="imports"><div className="title"><div><p className="eyebrow">RECENT IMPORTS</p><h2>导入记录</h2></div><button className="link" onClick={loadTeacherData}>刷新　→</button></div>{teacherUploads.length?teacherUploads.map((item)=><Import key={item.id} name={item.filename} details={`${item.subject||"未分类"} · ${new Date(item.created_at).toLocaleString("zh-CN")}`} state={item.status==="published"?"已发布":"待审核"}/>):<Import name="尚未上传试卷" details="上传后会显示在这里" state="待审核"/>}</article><article className="imports"><div className="title"><div><p className="eyebrow">QUESTION REVIEW</p><h2>题目审核</h2></div></div>{teacherQuestions.length?teacherQuestions.map((item)=><div className="import" key={item.id}><i>{item.subject.slice(0,3)}</i><span><b>{item.prompt}</b><small>{item.uploads?.filename||"手动建立"} · {item.answer_confirmed?"答案已确认":"需确认答案"}</small></span><em className={item.status==="published"?"published":"review"}>{item.status==="published"?"已发布":"待审核"}</em>{item.status!=="published"&&(!item.answer_confirmed?<button onClick={()=>confirmAnswer(item.id)}>确认答案</button>:<button onClick={()=>publishQuestion(item.id)}>发布</button>)}</div>):<div className="import"><i>ABCD</i><span><b>尚无待审核题目</b><small>上传 PDF 或手动新增题目后会显示在这里。</small></span></div>}</article></>}</section>}
  </main>;
}
function Import({name,details,state}:{name:string;details:string;state:string}){return <div className="import"><i>PDF</i><span><b>{name}</b><small>{details}</small></span><em className={state==="已发布"?"published":"review"}>{state}</em><button>{state==="已发布"?"查看":"审核"}</button></div>}
