"use client";

import { useMemo, useState } from "react";

type Question = { subject: string; text: string; options: string[]; answer: number; note: string };
const bank: Question[] = [
  { subject: "Bahasa Melayu", text: "Pilih ayat yang menggunakan kata kerja transitif dengan betul.", options: ["Adik tidur di sofa.", "Ibu membaca novel itu.", "Burung itu terbang tinggi.", "Mereka berjalan perlahan."], answer: 1, note: "‘Membaca’ diikuti objek ‘novel itu’." },
  { subject: "Matematik", text: "Nilai bagi 3(2x − 5) apabila x = 4 ialah", options: ["9", "12", "15", "24"], answer: 0, note: "3(2 × 4 − 5) = 9." },
  { subject: "Sejarah", text: "Apakah tujuan utama penubuhan Malayan Union pada tahun 1946?", options: ["Meluaskan kuasa raja Melayu", "Menyatukan pentadbiran negeri Melayu", "Menghapuskan kewarganegaraan", "Menubuhkan kerajaan persekutuan"], answer: 1, note: "Pentadbirannya disatukan di bawah kerajaan pusat." },
  { subject: "Biologi", text: "Struktur sel manakah mengawal semua aktiviti sel?", options: ["Membran sel", "Mitokondrion", "Nukleus", "Vakuol"], answer: 2, note: "Nukleus mengawal aktiviti sel." },
  { subject: "English", text: "Choose the sentence with the correct subject-verb agreement.", options: ["The students is ready.", "Each books are useful.", "Neither answer is correct.", "My friends goes home."], answer: 2, note: "‘Neither’ takes the singular verb ‘is’." },
];
const leaders = [["1","Nur Aina","20","08:42"],["2","陈宇轩","19","09:14"],["3","Siti Farah","19","10:02"],["4","Arjun K.","18","08:57"],["5","林嘉恩","18","11:20"]];
const subjects = ["Bahasa Melayu", "Matematik", "Sejarah", "Biologi", "English"];
const Logo = () => <div className="logo"><span>SPM</span><b>龙虎榜</b></div>;

export default function Home() {
  const [tab, setTab] = useState<"home"|"quiz"|"rank"|"teacher">("home");
  const [n, setN] = useState(0); const [answers, setAnswers] = useState<number[]>([]); const [done, setDone] = useState(false); const [isTeacher, setTeacher] = useState(false); const [choosing, setChoosing] = useState(false); const [selectedSubject, setSelectedSubject] = useState("Matematik"); const [quiz, setQuiz] = useState<Question[]>([]);
  const q = quiz[n] ?? bank[0]; const score = useMemo(() => answers.reduce((x,a,i) => x + (a === quiz[i]?.answer ? 1 : 0), 0), [answers, quiz]);
  function begin(subject = selectedSubject){const pool=bank.filter((item)=>item.subject===subject);setSelectedSubject(subject);setQuiz(Array.from({length:20},(_,i)=>pool[i%pool.length]));setN(0);setAnswers([]);setDone(false);setChoosing(false);setTab("quiz")}
  function pick(a:number){if(answers[n] !== undefined)return; const copy=[...answers];copy[n]=a;setAnswers(copy)}
  function advance(){n === quiz.length-1 ? setDone(true) : setN(n+1)}
  return <main>
    <header><button className="brand" onClick={()=>setTab("home")}><Logo/></button><div className="partner"><span>Powered by</span><img src="/myguru-logo.jpg" alt="myGuru" /></div><nav><button onClick={()=>setTab("rank")}>今日排行榜</button><button onClick={()=>setTab("teacher")}>教师中心</button></nav><button className="user"><i>陈</i><span><b>陈同学</b><small>连续打卡 7 天</small></span></button></header>
    {tab === "home" && <section className="wrap home">
      <div className="hero"><div><p className="eyebrow">MONDAY · 17 AUGUST</p><h1>今天，也比昨天<br/>更靠近 <em>A+</em>。</h1><p>选择今天要冲刺的科目，完成 20 题点亮学习记录。</p><button className="primary light" onClick={()=>setChoosing(true)}>选择科目开始　→</button></div><aside><p>本月学习足迹</p><div className="week">{"MTWTFSS".split("").map((x,i)=><span className={i<5?"checked":""} key={i}><b>{x}</b><i>{i<5?"✓":""}</i></span>)}</div><div className="streak"><strong>7</strong><span>天连续打卡<br/>继续保持！</span></div></aside></div>
      {choosing && <section className="subject-picker"><div><p className="eyebrow">CHOOSE YOUR SUBJECT</p><h2>今天想挑战哪一科？</h2><p>每日首轮选定后不可更换，完成该科 20 题将计入日榜。</p></div><div className="subject-grid">{subjects.map((subject)=><button className={subject===selectedSubject?"chosen":""} onClick={()=>setSelectedSubject(subject)} key={subject}><b>{subject}</b><small>20 题练习</small></button>)}</div><footer><button className="secondary" onClick={()=>setChoosing(false)}>稍后再说</button><button className="primary" onClick={()=>begin()}>开始 {selectedSubject}　→</button></footer></section>}
      <div className="cards"><article><div className="title"><div><p className="eyebrow">DAILY MISSION</p><h2>今日任务</h2></div><b className="pill">{selectedSubject}</b></div><div className="mission"><div className="circle"><b>0%</b><small>完成度</small></div><div><h3>{selectedSubject} · 20 题</h3><p>自主选择科目 · 完成后计入全校日榜</p><div className="bar"><i/></div><small>0 / 20 题</small></div></div><button className="link" onClick={()=>setChoosing(true)}>更换科目 / 开始答题　→</button></article><article><div className="title"><div><p className="eyebrow">SCHOOL RANKING</p><h2>今日龙虎榜</h2></div><button className="link" onClick={()=>setTab("rank")}>查看全部　→</button></div><div className="mini">{leaders.slice(0,3).map(([r,name,points])=><div key={r}><strong>{r}</strong><i>{name[0]}</i><b>{name}</b><em>{points} <small>题正确</small></em></div>)}</div><p className="notice">你的排名将在完成挑战后出现</p></article></div>
    </section>}
    {tab === "quiz" && <section className="wrap quiz">
      {!done ? <><div className="quizhead"><button className="link" onClick={()=>setTab("home")}>← 返回</button><div><span>{selectedSubject} · 第 {n+1} / 20 题</span><div className="bar"><i style={{width:`${((n+(answers[n]!==undefined?1:0))/20)*100}%`}}/></div></div><span>◷ 19:46</span></div><article className="question"><b className="subject">{q.subject}</b><h1>{q.text}</h1><div className="options">{q.options.map((v,i)=><button key={v} className={answers[n]===i?"selected":""} onClick={()=>pick(i)}><b>{"ABCD"[i]}</b><span>{v}</span></button>)}</div><footer><small>选择一个答案后继续</small><button disabled={answers[n]===undefined} className="primary" onClick={advance}>{n===quiz.length-1?"提交答案":"下一题　→"}</button></footer></article></> : <article className="result"><div>✦　✧　✦</div><p className="eyebrow">{selectedSubject.toUpperCase()} · DAILY MISSION COMPLETE</p><h1>今日挑战完成！</h1><strong>{score}<small>/ 20 题答对</small></strong><p>你的正式每日任务已提交。继续练习不会影响今日排名。</p><button className="primary" onClick={()=>setTab("rank")}>查看今日排名</button><button className="secondary" onClick={()=>setTab("home")}>返回首页</button><section>{quiz.map((x,i)=><div key={`${x.subject}-${i}`}><b className={answers[i]===x.answer?"ok":"bad"}>{answers[i]===x.answer?"✓":"×"}</b><span>{i+1}. {x.subject}</span><small>{answers[i]===x.answer?"正确":`答案：${"ABCD"[x.answer]} · ${x.note}`}</small></div>)}</section></article>}</section>}
    {tab === "rank" && <section className="wrap page"><div className="heading"><div><p className="eyebrow">17 AUGUST · MALAYSIA TIME</p><h1>今日龙虎榜</h1><p>按首轮 20 题正确数排列。相同成绩以完成时间排序。</p></div><b>♛</b></div><div className="rank-subjects">{subjects.map((subject)=><button className={subject===selectedSubject?"active":""} onClick={()=>setSelectedSubject(subject)} key={subject}>{subject}</button>)}</div><article className="table"><div className="thead"><span>排名</span><span>学生</span><span>正确题数</span><span>完成时间</span></div>{leaders.map(([r,name,points,time])=><div className="tr" key={name}><strong>{r}</strong><span><i>{name[0]}</i><b>{name}</b></span><span><b>{points}</b> / 20</span><small>{time}</small></div>)}<div className="tr mine"><strong>—</strong><span><i>陈</i><b>陈同学（你）</b></span><span>尚未完成</span><small>—</small></div></article></section>}
    {tab === "teacher" && <section className="wrap page"><div className="teacherhero"><div><p className="eyebrow">TEACHER STUDIO</p><h1>让每一份练习，<br/>成为学生的下一步。</h1><p>上传文字型 PDF，审核题目后发布到全校练习题库。</p></div><b>A<small>B　C　D</small></b></div>{!isTeacher?<article className="invite"><i>⌁</i><div><h2>进入教师中心</h2><p>首次使用请输入教师邀请码。验证后，此 Google 帐号将获得题库管理权限。</p></div><button className="primary" onClick={()=>setTeacher(true)}>验证邀请码　→</button></article>:<><article className="upload"><i>↑</i><h2>上传新的试卷</h2><p>支持文字型 PDF · 系统会将 ABCD 选择题提取为待审核草稿</p><button className="secondary">选择 PDF 文件</button></article><article className="imports"><div className="title"><div><p className="eyebrow">RECENT IMPORTS</p><h2>导入记录</h2></div><button className="link">查看所有题目　→</button></div><Import name="SPM Trial Mathematics 2026.pdf" details="今日 10:24 · 40 道题已发布" state="已发布"/><Import name="Sejarah Bab 4 Latihan.pdf" details="昨日 16:40 · 12 道题等待审核" state="待审核"/></article></>}</section>}
  </main>;
}
function Import({name,details,state}:{name:string;details:string;state:string}){return <div className="import"><i>PDF</i><span><b>{name}</b><small>{details}</small></span><em className={state==="已发布"?"published":"review"}>{state}</em><button>{state==="已发布"?"查看":"审核"}</button></div>}
