export type BankQuestion = {
  sourceKey: string;
  subject: string;
  prompt: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: "A" | "B" | "C" | "D";
  explanation: string;
  difficulty: "基础" | "中等" | "进阶";
};

type Row = Omit<BankQuestion, "sourceKey">;
const make = (prefix: string, rows: Row[]): BankQuestion[] =>
  rows.map((row, index) => ({ ...row, sourceKey: `myguru-spm-v1-${prefix}-${String(index + 1).padStart(2, "0")}` }));
const q = (subject: string, prompt: string, a: string, b: string, c: string, d: string, answer: BankQuestion["correctOption"], explanation: string, difficulty: BankQuestion["difficulty"] = "基础"): Row => ({ subject, prompt, optionA: a, optionB: b, optionC: c, optionD: d, correctOption: answer, explanation, difficulty });

const mathematics = make("mathematics", [
  q("Matematik", "Calculate / Hitung: 3/4 + 1/8 =", "5/8", "7/8", "1", "3/8", "B", "Use denominator 8: 3/4 = 6/8, so 6/8 + 1/8 = 7/8."),
  q("Matematik", "Solve / Selesaikan: 2x + 5 = 17.", "x = 5", "x = 6", "x = 11", "x = 22", "B", "2x = 12, hence x = 6."),
  q("Matematik", "What is 15% of 240? / Apakah 15% daripada 240?", "24", "30", "36", "45", "C", "0.15 × 240 = 36."),
  q("Matematik", "A rectangle is 8 cm by 5 cm. Its area is", "13 cm²", "26 cm²", "40 cm²", "80 cm²", "C", "Area = length × width = 8 × 5."),
  q("Matematik", "Find the gradient of the line through (2, 3) and (6, 11).", "1/2", "2", "4", "8", "B", "Gradient = (11 − 3)/(6 − 2) = 8/4 = 2."),
  q("Matematik", "The mean of 4, 6, 8 and 12 is", "6", "7", "7.5", "8", "C", "(4 + 6 + 8 + 12) ÷ 4 = 7.5."),
  q("Matematik", "Simplify / Ringkaskan: 5a − 2a + 3.", "3a", "3a + 3", "7a + 3", "10a", "B", "Combine like terms: 5a − 2a = 3a."),
  q("Matematik", "A bag has 3 red and 2 blue balls. P(blue) is", "2/3", "2/5", "3/5", "1/2", "B", "There are 2 blue balls out of 5 balls."),
  q("Matematik", "Convert 0.375 to a fraction in simplest form.", "3/5", "3/8", "5/8", "375/100", "B", "0.375 = 375/1000 = 3/8."),
  q("Matematik", "The circumference of a circle of radius 7 cm, using π = 22/7, is", "14 cm", "22 cm", "44 cm", "154 cm", "C", "C = 2πr = 2 × 22/7 × 7 = 44."),
  q("Matematik", "If y = 3x − 4, find y when x = 5.", "7", "11", "15", "19", "B", "y = 3(5) − 4 = 11."),
  q("Matematik", "Find the HCF of 18 and 24.", "3", "6", "9", "72", "B", "The greatest common factor is 6."),
  q("Matematik", "A price is reduced from RM80 to RM68. The discount percentage is", "10%", "12%", "15%", "20%", "C", "Discount = RM12; 12/80 × 100% = 15%."),
  q("Matematik", "Which is a prime number?", "21", "27", "29", "35", "C", "29 has only 1 and 29 as factors."),
  q("Matematik", "The interior angles of a triangle add up to", "90°", "180°", "270°", "360°", "B", "The angle sum of any triangle is 180°."),
  q("Matematik", "Solve: x² = 49, where x is positive.", "5", "6", "7", "14", "C", "The positive square root of 49 is 7."),
  q("Matematik", "A car travels 150 km in 3 hours. Its average speed is", "30 km/h", "50 km/h", "75 km/h", "450 km/h", "B", "Speed = distance ÷ time = 150 ÷ 3."),
  q("Matematik", "What is the next term: 2, 5, 8, 11, ...?", "12", "13", "14", "15", "C", "The sequence increases by 3."),
  q("Matematik", "Express 2.5 km in metres.", "25 m", "250 m", "2 500 m", "25 000 m", "C", "1 km = 1 000 m."),
  q("Matematik", "A right angle is", "45°", "90°", "180°", "360°", "B", "A right angle measures 90°."),
  q("Matematik", "Find 2³ × 2⁴.", "2⁷", "4⁷", "2¹²", "2¹", "A", "For the same base, add the indices: 3 + 4 = 7."),
  q("Matematik", "The median of 3, 7, 9, 11, 15 is", "7", "9", "10", "11", "B", "The middle value is 9."),
  q("Matematik", "A square has perimeter 36 cm. Its side length is", "6 cm", "8 cm", "9 cm", "12 cm", "C", "Each side = 36 ÷ 4 = 9 cm."),
  q("Matematik", "What is √81?", "7", "8", "9", "18", "C", "9 × 9 = 81."),
  q("Matematik", "If 4 notebooks cost RM12, the cost of 7 notebooks at the same rate is", "RM18", "RM20", "RM21", "RM24", "C", "One notebook costs RM3, so 7 cost RM21."),
  q("Matematik", "The volume of a cuboid 4 cm × 3 cm × 5 cm is", "12 cm³", "20 cm³", "47 cm³", "60 cm³", "D", "Volume = 4 × 3 × 5."),
  q("Matematik", "Find x: 5(x − 2) = 20.", "2", "4", "6", "8", "C", "x − 2 = 4, therefore x = 6."),
  q("Matematik", "Which ratio is equivalent to 2 : 3?", "4 : 5", "4 : 6", "5 : 6", "6 : 8", "B", "Multiply both terms by 2."),
  q("Matematik", "A regular hexagon has how many sides?", "5", "6", "7", "8", "B", "A hexagon has six sides."),
  q("Matematik", "Calculate: −7 + 12.", "−19", "−5", "5", "19", "C", "Adding 12 to −7 gives 5."),
  q("Matematik", "The mode of 2, 4, 4, 5, 7 is", "2", "4", "5", "7", "B", "4 occurs most frequently."),
  q("Matematik", "If a = 4 and b = 3, find 2a + b.", "7", "8", "11", "14", "C", "2(4) + 3 = 11."),
  q("Matematik", "Which fraction is largest?", "1/2", "2/3", "3/5", "5/8", "B", "2/3 is approximately 0.667, larger than the others."),
  q("Matematik", "The complement of 37° is", "43°", "53°", "127°", "143°", "B", "Complementary angles add to 90°: 90 − 37."),
  q("Matematik", "A map scale is 1 : 50 000. 2 cm on the map represents", "100 m", "500 m", "1 km", "10 km", "C", "2 × 50 000 cm = 100 000 cm = 1 km."),
  q("Matematik", "Find the simple interest on RM1 000 at 5% per annum for 2 years.", "RM50", "RM100", "RM150", "RM1 100", "B", "I = PRT = 1000 × 0.05 × 2."),
  q("Matematik", "The probability of getting an even number on a fair six-sided die is", "1/6", "1/3", "1/2", "2/3", "C", "The even outcomes are 2, 4 and 6: 3 out of 6."),
  q("Matematik", "Expand: (x + 3)(x + 2).", "x² + 5x + 6", "x² + 6", "x² + 5x", "x² + 6x + 5", "A", "Multiply every term: x² + 2x + 3x + 6."),
  q("Matematik", "A number increased by 9 is 24. The number is", "13", "15", "24", "33", "B", "Subtract 9 from 24."),
  q("Matematik", "The area of a triangle with base 10 cm and height 6 cm is", "16 cm²", "30 cm²", "60 cm²", "120 cm²", "B", "Area = 1/2 × base × height = 30 cm²."),
]);

const science = make("science", [
  q("Sains", "Which organ pumps blood around the human body? / Organ manakah mengepam darah?", "Lung / Paru-paru", "Heart / Jantung", "Kidney / Buah pinggang", "Stomach / Perut", "B", "The heart pumps blood through the circulatory system."),
  q("Sains", "Photosynthesis requires sunlight, water and", "oxygen", "carbon dioxide", "nitrogen", "helium", "B", "Plants use carbon dioxide to make food during photosynthesis."),
  q("Sains", "The SI unit of force is", "joule", "watt", "newton", "pascal", "C", "Force is measured in newtons (N)."),
  q("Sains", "Which is a renewable energy source?", "Coal", "Natural gas", "Solar energy", "Petroleum", "C", "Solar energy is naturally replenished."),
  q("Sains", "The change from liquid to gas is called", "freezing", "melting", "condensation", "evaporation", "D", "Evaporation changes a liquid into a gas."),
  q("Sains", "A solution with pH 3 is", "acidic", "neutral", "alkaline", "salty", "A", "A pH lower than 7 is acidic."),
  q("Sains", "Which blood component helps blood clot?", "Red blood cell", "Platelet", "Plasma", "White blood cell", "B", "Platelets help stop bleeding by clotting."),
  q("Sains", "The centre of an atom contains", "electrons only", "protons and neutrons", "neutrons and electrons", "protons only", "B", "The nucleus contains protons and neutrons."),
  q("Sains", "Which instrument measures electric current?", "Voltmeter", "Ammeter", "Thermometer", "Barometer", "B", "An ammeter is connected to measure current."),
  q("Sains", "Friction usually acts", "in the direction of motion", "opposite to motion", "upwards only", "towards the centre only", "B", "Friction resists relative motion between surfaces."),
  q("Sains", "Which gas is most abundant in air?", "Oxygen", "Carbon dioxide", "Nitrogen", "Argon", "C", "Nitrogen makes up about 78% of air."),
  q("Sains", "A convex lens can form a", "real image", "sound wave", "magnetic field", "chemical bond", "A", "A convex lens can form a real image when the object is beyond its focal length."),
  q("Sains", "The process by which green plants make glucose is", "respiration", "digestion", "photosynthesis", "transpiration", "C", "Photosynthesis produces glucose using light energy."),
  q("Sains", "Which is a conductor of electricity?", "Rubber", "Plastic", "Copper", "Wood", "C", "Copper has free electrons and conducts electricity."),
  q("Sains", "The planet known as the Red Planet is", "Venus", "Mars", "Jupiter", "Saturn", "B", "Mars appears red because of iron oxide on its surface."),
  q("Sains", "Which system controls and coordinates body responses?", "Digestive system", "Nervous system", "Respiratory system", "Skeletal system", "B", "The nervous system coordinates rapid responses."),
  q("Sains", "What happens to particles when a substance is heated?", "They stop moving", "They move faster", "They disappear", "They become heavier", "B", "Heating increases particles’ kinetic energy."),
  q("Sains", "Which substance is an alkali?", "Hydrochloric acid", "Sodium hydroxide", "Vinegar", "Lemon juice", "B", "Sodium hydroxide is an alkali."),
  q("Sains", "The unit of electrical power is", "ampere", "volt", "watt", "ohm", "C", "Electrical power is measured in watts (W)."),
  q("Sains", "Which vitamin is produced in the skin with sunlight?", "Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K", "C", "Sunlight helps the skin produce vitamin D."),
  q("Sains", "Which part of a flower develops into a fruit after fertilisation?", "Petal", "Anther", "Ovary", "Sepal", "C", "The ovary develops into a fruit."),
  q("Sains", "A magnet attracts objects made of", "aluminium", "iron", "glass", "paper", "B", "Iron is a magnetic material."),
  q("Sains", "Sound cannot travel through", "water", "air", "steel", "vacuum", "D", "Sound needs particles; a vacuum has none."),
  q("Sains", "Which process separates sand from water?", "Filtration", "Distillation", "Chromatography", "Evaporation", "A", "Filter paper traps insoluble sand."),
  q("Sains", "The ozone layer helps protect Earth from", "infrared rays", "ultraviolet radiation", "sound waves", "radio waves", "B", "Ozone absorbs much harmful UV radiation."),
  q("Sains", "Which is an example of a decomposer?", "Grass", "Mushroom", "Eagle", "Rabbit", "B", "Fungi such as mushrooms break down dead material."),
  q("Sains", "The formula for speed is", "distance × time", "distance ÷ time", "time ÷ distance", "mass × acceleration", "B", "Speed is distance travelled per unit time."),
  q("Sains", "Which structure controls substances entering and leaving a cell?", "Cell wall", "Cell membrane", "Vacuole", "Nucleus", "B", "The cell membrane controls movement of substances."),
  q("Sains", "Rusting of iron needs water and", "oxygen", "carbon dioxide", "nitrogen", "light", "A", "Both oxygen and water are required for rusting."),
  q("Sains", "Which simple machine is a ramp?", "Lever", "Pulley", "Inclined plane", "Wheel and axle", "C", "A ramp is an inclined plane."),
  q("Sains", "The boiling point of pure water at normal pressure is", "0°C", "50°C", "100°C", "273°C", "C", "Pure water boils at 100°C at one atmosphere."),
  q("Sains", "Which organ removes urea from the blood?", "Liver", "Kidney", "Skin", "Pancreas", "B", "Kidneys filter blood and remove urea in urine."),
  q("Sains", "A series circuit has", "one path for current", "two batteries only", "no resistance", "parallel branches only", "A", "Current has one continuous path in a series circuit."),
  q("Sains", "Which particle has a negative charge?", "Proton", "Neutron", "Electron", "Nucleus", "C", "Electrons carry negative charge."),
  q("Sains", "The greenhouse effect is mainly increased by", "carbon dioxide", "oxygen", "hydrogen", "nitrogen", "A", "Carbon dioxide is a greenhouse gas."),
  q("Sains", "Which material is best for a saucepan handle?", "Copper", "Aluminium", "Plastic", "Iron", "C", "Plastic is a poor conductor of heat."),
  q("Sains", "Respiration releases", "only water", "energy from food", "chlorophyll", "soil minerals", "B", "Cells release energy from glucose during respiration."),
  q("Sains", "An object floats when its density is", "greater than water", "less than water", "equal to zero", "always 1 g cm⁻³", "B", "An object less dense than water floats."),
  q("Sains", "Which type of wave is light?", "Mechanical wave", "Electromagnetic wave", "Water wave", "Sound wave", "B", "Light can travel through a vacuum, so it is electromagnetic."),
  q("Sains", "Which practice reduces household waste?", "Burning plastics", "Recycling materials", "Throwing rubbish into rivers", "Using more disposable items", "B", "Recycling conserves resources and reduces waste."),
]);

const bahasaMelayu = make("bahasa-melayu", [
  q("Bahasa Melayu", "Pilih kata ganda yang betul: ‘Kanak-kanak itu bermain di ____.’", "taman", "taman-taman", "bertaman", "ketamanan", "A", "Kata nama ‘taman’ tidak perlu digandakan dalam ayat ini."),
  q("Bahasa Melayu", "Sinonim bagi perkataan ‘rajin’ ialah", "malas", "tekun", "lambat", "cuai", "B", "‘Tekun’ membawa maksud rajin dan bersungguh-sungguh."),
  q("Bahasa Melayu", "Pilih ayat yang menggunakan kata sendi nama dengan betul.", "Ali pergi di sekolah.", "Ali pergi ke sekolah.", "Ali pergi daripada sekolah.", "Ali pergi akan sekolah.", "B", "Kata sendi ‘ke’ menunjukkan arah atau tempat."),
  q("Bahasa Melayu", "Antonim bagi ‘tinggi’ ialah", "besar", "rendah", "panjang", "jauh", "B", "Antonim ialah perkataan yang berlawan makna."),
  q("Bahasa Melayu", "Pilih penjodoh bilangan yang sesuai: ‘se____ kunci’.", "buah", "batang", "utas", "helai", "A", "Penjodoh bilangan untuk kunci ialah ‘buah’."),
  q("Bahasa Melayu", "Peribahasa ‘bagai aur dengan tebing’ bermaksud", "hidup bersendirian", "saling membantu", "cepat marah", "suka menunjuk-nunjuk", "B", "Aur dan tebing saling memerlukan antara satu sama lain."),
  q("Bahasa Melayu", "Kata kerja transitif dalam ayat ‘Siti membaca buku’ ialah", "Siti", "membaca", "buku", "ialah", "B", "Kata kerja transitif memerlukan objek, iaitu ‘buku’."),
  q("Bahasa Melayu", "Pilih ejaan yang betul.", "aktiviti", "aktibiti", "aktivity", "aktivitii", "A", "Ejaan baku ialah ‘aktiviti’."),
  q("Bahasa Melayu", "‘Walaupun hujan lebat, mereka tetap hadir.’ Kata hubung dalam ayat ini ialah", "hujan", "lebat", "walaupun", "hadir", "C", "‘Walaupun’ menghubungkan dua bahagian ayat."),
  q("Bahasa Melayu", "Pilih imbuhan yang betul: ‘Dia sedang ____ surat.’", "tulis", "menulis", "ditulis", "penulis", "B", "Kata kerja aktif yang sesuai ialah ‘menulis’."),
  q("Bahasa Melayu", "Maksud simpulan bahasa ‘ringan tulang’ ialah", "kurus", "rajin bekerja", "suka bergurau", "cepat berjalan", "B", "‘Ringan tulang’ bermaksud rajin dan suka membantu."),
  q("Bahasa Melayu", "Pilih ayat pasif yang betul.", "Buku itu membaca oleh Amir.", "Buku itu dibaca oleh Amir.", "Amir dibaca buku itu.", "Membaca buku itu oleh Amir.", "B", "Kata kerja pasif menggunakan imbuhan ‘di-’."),
  q("Bahasa Melayu", "Kata adjektif dalam ayat ‘Bunga itu sangat cantik’ ialah", "Bunga", "itu", "sangat", "cantik", "D", "‘Cantik’ menerangkan sifat bunga."),
  q("Bahasa Melayu", "Pilih kata nama khas.", "sekolah", "Malaysia", "bandar", "guru", "B", "‘Malaysia’ ialah nama khusus negara."),
  q("Bahasa Melayu", "Ayat manakah menggunakan tanda baca dengan betul?", "Ibu berkata “Jangan lewat.”", "Ibu berkata, “Jangan lewat.”", "Ibu berkata “Jangan lewat”.", "Ibu berkata, “Jangan lewat”.", "B", "Koma digunakan sebelum petikan langsung dan noktah berada dalam petikan."),
  q("Bahasa Melayu", "Pilih kata majmuk yang betul.", "kerjasama", "kerja sama", "bekerjasama", "bekerja sama", "B", "‘Kerja sama’ ialah kata majmuk yang dieja terpisah."),
  q("Bahasa Melayu", "‘Murid-murid sedang ____ di padang.’", "berlari", "lari", "pelari", "dilarikan", "A", "Kata kerja aktif berimbuhan ‘ber-’ sesuai dalam ayat ini."),
  q("Bahasa Melayu", "Maksud peribahasa ‘sediakan payung sebelum hujan’ ialah", "membeli payung", "membuat persediaan awal", "mengelakkan hujan", "menunggu bantuan", "B", "Peribahasa ini menekankan persediaan sebelum masalah berlaku."),
  q("Bahasa Melayu", "Pilih kata tanya yang sesuai: ‘____ nama kamu?’", "Bila", "Siapa", "Apa", "Mengapa", "C", "Kata tanya ‘apa’ digunakan untuk menanyakan nama."),
  q("Bahasa Melayu", "Kata seerti bagi ‘gembira’ ialah", "sedih", "dukacita", "suka", "marah", "C", "‘Suka’ mempunyai makna yang hampir sama dengan gembira."),
  q("Bahasa Melayu", "Pilih ayat yang gramatis.", "Saya sudah makan nasi.", "Saya sudah memakan nasi-nasi.", "Saya sudah makan akan nasi.", "Saya telah dimakan nasi.", "A", "Ayat A ringkas dan menggunakan struktur yang betul."),
  q("Bahasa Melayu", "Kata hubung pancangan relatif ialah", "dan", "atau", "yang", "tetapi", "C", "‘Yang’ menghubungkan klausa relatif dengan kata nama."),
  q("Bahasa Melayu", "Pilih kata pemeri yang betul: ‘Hobi saya ____ membaca.’", "adalah", "ialah", "akan", "dengan", "A", "‘Adalah’ digunakan sebelum frasa kerja atau frasa adjektif."),
  q("Bahasa Melayu", "Apakah maksud ‘murni’?","bersih daripada sifat buruk", "pahit", "bising", "lemah", "A", "Murni bermaksud suci dan bersih daripada unsur buruk."),
  q("Bahasa Melayu", "Pilih kata arah yang sesuai: ‘Kucing itu tidur ____ meja.’", "ke", "dari", "di bawah", "daripada", "C", "‘Di bawah’ menunjukkan kedudukan."),
  q("Bahasa Melayu", "Pilih ayat seruan.", "Adakah kamu sudah makan?", "Wah, cantiknya pemandangan ini!", "Tolong tutup pintu itu.", "Mereka bermain bola.", "B", "Ayat seruan menyatakan perasaan seperti kagum."),
  q("Bahasa Melayu", "Kata lawan bagi ‘awal’ ialah", "cepat", "lambat", "akhir", "segera", "C", "Awal dan akhir ialah antonim."),
  q("Bahasa Melayu", "‘Dia ____ ke pasar setiap pagi.’", "pergi", "perginya", "pergiannya", "dipergi", "A", "Kata kerja dasar ‘pergi’ sesuai dalam ayat ini."),
  q("Bahasa Melayu", "Pilih imbuhan apitan yang betul: ‘____ negara perlu dipelihara.’", "Keindahan", "Indah", "Mengindah", "Terindah", "A", "Ke-...-an membentuk kata nama abstrak ‘keindahan’."),
  q("Bahasa Melayu", "Apakah fungsi kata nafi ‘tidak’?","Menafikan frasa kerja atau frasa adjektif", "Menunjukkan bilangan", "Menunjukkan tempat", "Menghubungkan ayat", "A", "‘Tidak’ menafikan kata kerja dan kata adjektif."),
  q("Bahasa Melayu", "Pilih kata bilangan tentu.", "beberapa", "semua", "dua", "para", "C", "‘Dua’ menunjukkan bilangan yang tepat."),
  q("Bahasa Melayu", "Maksud ‘besar kepala’ ialah", "mempunyai kepala besar", "sombong", "pandai", "pening", "B", "Simpulan bahasa ‘besar kepala’ bermaksud sombong."),
  q("Bahasa Melayu", "Pilih kata ganti nama diri pertama.", "dia", "mereka", "saya", "kamu", "C", "‘Saya’ merujuk kepada penutur."),
  q("Bahasa Melayu", "Pilih ayat perintah.", "Jangan buang sampah merata-rata.", "Mereka membuang sampah.", "Siapakah yang membuang sampah?", "Alangkah bersihnya kelas ini!", "A", "Ayat perintah memberi arahan atau larangan."),
  q("Bahasa Melayu", "Kata dasar bagi ‘makanan’ ialah", "makan", "makanan", "memakan", "dimakan", "A", "Kata dasar ialah ‘makan’."),
  q("Bahasa Melayu", "‘Kami belajar ____ perpustakaan.’", "dengan", "di", "kepada", "daripada", "B", "Kata sendi ‘di’ digunakan untuk tempat."),
  q("Bahasa Melayu", "Pilih perkataan yang mempunyai vokal berganding.", "air", "buku", "rumah", "kelas", "A", "‘Ai’ dalam ‘air’ ialah vokal berganding."),
  q("Bahasa Melayu", "Pilih kata adjektif ukuran.", "merah", "tinggi", "manis", "cepat", "B", "‘Tinggi’ menerangkan ukuran."),
  q("Bahasa Melayu", "Ayat ‘Mereka akan pulang esok’ menggunakan kata", "bantu", "arah", "tanya", "seru", "A", "‘Akan’ ialah kata bantu aspek/waktu."),
  q("Bahasa Melayu", "Pilih penanda wacana yang sesuai untuk menunjukkan kesimpulan.", "Namun", "Selain itu", "Oleh itu", "Contohnya", "C", "‘Oleh itu’ menunjukkan rumusan atau kesimpulan."),
]);

const english = make("english", [
  q("English", "Choose the correct word: ‘She ____ to school every day.’", "walk", "walks", "walking", "walked", "B", "With ‘she’ in the present simple, use ‘walks’."),
  q("English", "The synonym of ‘happy’ is", "angry", "cheerful", "tired", "quiet", "B", "‘Cheerful’ has a similar meaning to happy."),
  q("English", "Choose the correct article: ‘I saw ____ elephant.’", "a", "an", "the", "no article", "B", "Use ‘an’ before a vowel sound."),
  q("English", "Which sentence is in the past tense?", "They play football.", "They are playing football.", "They played football.", "They will play football.", "C", "‘Played’ is the simple past form."),
  q("English", "Choose the antonym of ‘ancient’.", "old", "historic", "modern", "traditional", "C", "Modern is the opposite of ancient."),
  q("English", "‘The children ____ watching television now.’", "is", "are", "was", "be", "B", "The plural subject ‘children’ takes ‘are’."),
  q("English", "Which word is a noun?", "beautiful", "quickly", "teacher", "write", "C", "A teacher is a person; it is a noun."),
  q("English", "Choose the correct preposition: ‘The book is ____ the table.’", "in", "on", "at", "from", "B", "We say ‘on the table’."),
  q("English", "The plural of ‘child’ is", "childs", "childes", "children", "childrens", "C", "‘Children’ is the irregular plural form."),
  q("English", "Choose the correct question word: ‘____ are you late?’", "What", "Where", "Why", "Who", "C", "‘Why’ asks for a reason."),
  q("English", "Which sentence has correct punctuation?", "Where are you going.", "Where are you going?", "where are you going?", "Where are you going!", "B", "A direct question ends with a question mark."),
  q("English", "Complete: ‘If it rains, we ____ at home.’", "stay", "stayed", "will stay", "staying", "C", "In a first conditional sentence, the result clause uses ‘will’."),
  q("English", "The comparative form of ‘good’ is", "gooder", "more good", "better", "best", "C", "‘Better’ is the irregular comparative form."),
  q("English", "Choose the correct pronoun: ‘Aina and I finished ____ homework.’", "our", "their", "his", "her", "A", "The possessive pronoun for Aina and I is ‘our’."),
  q("English", "Which word is an adjective?", "carefully", "kind", "kindness", "kindly", "B", "‘Kind’ describes a noun, so it is an adjective."),
  q("English", "‘He has lived here ____ 2019.’", "for", "since", "from", "at", "B", "Use ‘since’ with a starting point in time."),
  q("English", "Choose the correct passive voice: ‘The chef cooked the meal.’", "The meal cooked the chef.", "The meal was cooked by the chef.", "The chef was cooked by the meal.", "The meal is cook by the chef.", "B", "The object becomes the subject: ‘was cooked by’."),
  q("English", "The idiom ‘a piece of cake’ means", "a dessert", "very easy", "very expensive", "a celebration", "B", "It means something is easy to do."),
  q("English", "Choose the correct spelling.", "separate", "seperate", "seperete", "separrate", "A", "The correct spelling is ‘separate’."),
  q("English", "Which is a conjunction?", "because", "quickly", "garden", "blue", "A", "‘Because’ joins ideas and gives a reason."),
  q("English", "Complete: ‘There ____ many books on the shelf.’", "is", "are", "was", "has", "B", "Use ‘are’ with plural noun ‘books’."),
  q("English", "The opposite of ‘borrow’ is", "lend", "take", "keep", "receive", "A", "To lend is to give something for temporary use."),
  q("English", "Choose the correct form: ‘My brother is ____ than me.’", "tall", "taller", "tallest", "more tall", "B", "Use the comparative ‘taller’ when comparing two people."),
  q("English", "Which sentence uses a modal verb?", "She sings well.", "She can sing well.", "She sang well.", "She is singing well.", "B", "‘Can’ is a modal verb expressing ability."),
  q("English", "Choose the correct word: ‘The students ____ their project yesterday.’", "finish", "finished", "finishing", "will finish", "B", "‘Yesterday’ signals the past tense ‘finished’."),
  q("English", "A person who writes books is an", "actor", "author", "artist", "athlete", "B", "An author writes books."),
  q("English", "Which word is an adverb?", "slow", "slowness", "slowly", "slower", "C", "‘Slowly’ describes how an action is done."),
  q("English", "Complete: ‘Neither Amir nor his friends ____ ready.’", "is", "are", "was", "be", "B", "The verb agrees with the nearer plural subject ‘friends’."),
  q("English", "Choose the sentence with a possessive apostrophe.", "The dogs tail is long.", "The dog's tail is long.", "The dogs' tail is long.", "The dog's tail are long.", "B", "One dog owns the tail, so use dog’s."),
  q("English", "‘Although’ is used to show", "addition", "contrast", "time", "place", "B", "Although introduces an unexpected contrast."),
  q("English", "The main idea of a paragraph is", "a minor detail", "the central message", "the title only", "the last word", "B", "The main idea tells what the paragraph is mostly about."),
  q("English", "Choose the correct reported speech: Ali said, ‘I am tired.’", "Ali said that I am tired.", "Ali said that he was tired.", "Ali said that he is tired.", "Ali says that he was tired.", "B", "In reported speech, ‘I am’ changes to ‘he was’."),
  q("English", "Which word has a prefix meaning ‘not’?", "unhappy", "replay", "teacher", "careful", "A", "The prefix ‘un-’ means not."),
  q("English", "Complete: ‘We have ____ dinner already.’", "eat", "ate", "eaten", "eating", "C", "Present perfect uses ‘have’ + past participle ‘eaten’."),
  q("English", "Choose a polite request.", "Give me your pen.", "Could you lend me your pen, please?", "You must lend me your pen.", "Lend your pen now.", "B", "‘Could you… please?’ is polite."),
  q("English", "Which word is a collective noun?", "team", "players", "playing", "playful", "A", "A team is a group of people."),
  q("English", "The correct tag question is: ‘She is coming, ____?’", "is she", "isn't she", "does she", "doesn't she", "B", "A positive statement takes a negative tag with the same auxiliary."),
  q("English", "Choose the correct word: ‘This is the ____ book I have read.’", "interesting", "more interesting", "most interesting", "interestingly", "C", "Use the superlative after ‘the’."),
  q("English", "Which sentence is a command?", "Please close the window.", "Are you closing the window?", "The window is closed.", "What a large window!", "A", "An imperative sentence gives an instruction or request."),
  q("English", "A dictionary is mainly used to find", "the weather", "word meanings", "train times", "telephone numbers", "B", "Dictionaries provide meanings, spelling and usage of words."),
]);

export const starterQuestionBank = [...mathematics, ...science, ...bahasaMelayu, ...english];
